#
#   Copyright 2020-2021  SenX S.A.S.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#

name: Build WarpÂ 10 docker image

on:
  push:
    branches:
      - master
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2.4.0

      - name: Set tag
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Set fake tag
        if: startsWith(github.ref, 'refs/tags/') == false
        run: echo "TAG=master" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1.13.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the test image
        uses: docker/build-push-action@v2.8.0
        with:
          file: ./Dockerfile
          platforms: linux/amd64
          build-args: WARP10_VERSION=${{ env.TAG }}
          load: true
          tags: ${{ secrets.DOCKER_USERNAME }}/warp10:${{ env.TAG }}-test

      - name: Test the new image, default mode
        run: |
          ./test.sh "docker run -d -p 8080:8080 -p 8081:8081 ${{ secrets.DOCKER_USERNAME }}/warp10:${TAG}-test"

      - name: Test the new image, in_memory mode
        run: |
          ./test.sh "docker run -d -p 8080:8080 -p 8081:8081 -e IN_MEMORY=true ${{ secrets.DOCKER_USERNAME }}/warp10:${TAG}-test"

      - name: Build the main image
        uses: docker/build-push-action@v2.8.0
        with:
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          build-args: WARP10_VERSION=${{ env.TAG }}
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/warp10:latest
            ${{ secrets.DOCKER_USERNAME }}/warp10:${{ env.TAG }}

      - name: Build the ci image
        uses: docker/build-push-action@v2.8.0
        with:
          context: ./predictible-tokens-for-ci
          file: ./predictible-tokens-for-ci/Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          build-args: WARP10_VERSION=${{ env.TAG }}
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/warp10:${{ env.TAG }}-ci


      - name: Send Notification
        uses: bayssmekanique/action-simple-slack-notifier@v1.2.6
        if: always()
        with:
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          status: ${{ job.status }}
          channel: ${{ secrets.SLACK_CHANNEL }}
          version: ${{ steps.check.outputs.version }}